[package]
name = "zdriver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libz-sys = { path = "../libz-sys", default-features = false, features = ["libc","static"] }
